
Organizations:

    - &OrdererOrg
        Name: Orderer
        ID: orderer.${DOMAIN}
        MSPDir: ordererOrganizations/${DOMAIN}/msp

    - &firstOrg
        Name: ${ORG}
        ID: ${ORG}
        MSPDir: peerOrganizations/${ORG}.${DOMAIN}/msp
        AnchorPeers:
        # AnchorPeers defines the location of peers which can be used
        # for cross org gossip communication.  Note, this value is only
        # encoded in the genesis block in the Application section context
        - Host: peer0.${ORG}.${DOMAIN}
          Port: 7051

Capabilities:
  Global: &ChannelCapabilities
    V1_1: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Application: &ApplicationCapabilities
    V1_2: true



Orderer: &OrdererDefaults

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: ${ORDERER_BATCH_TIMEOUT}s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 98 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

Profiles:

    SoloOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: solo
            Addresses:
              - orderer.${DOMAIN}:7050
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities

        Consortiums:
            SampleConsortium:
                Organizations:
                    - *OrdererOrg

    RaftOrdererGenesis:
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        <<: *OrdererDefaults
        OrdererType: etcdraft
        Addresses: [${ORDERER_NAME}.${DOMAIN}:7050]
        EtcdRaft:
          # The set of Raft replicas for this network. For the etcd/raft-based
          # implementation, we expect every replica to also be an OSN. Therefore,
          # a subset of the host:port items enumerated in this list should be
          # replicated under the Orderer.Addresses key above.
          Consenters:
            - Host: ${ORDERER_NAME}.${DOMAIN}
              Port: 7050
              #                  ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft0.${DOMAIN}/msp/tlscacerts/tlsca.${DOMAIN}-cert.pem
              ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/${ORDERER_NAME}.${DOMAIN}/tls/server.crt
              ServerTLSCert: ordererOrganizations/${DOMAIN}/orderers/${ORDERER_NAME}.${DOMAIN}/tls/server.crt
        Organizations:
          - *OrdererOrg
        Capabilities:
          <<: *OrdererCapabilities

      Consortiums:
        SampleConsortium:
          Organizations:
            - *OrdererOrg



    Raft3OrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            Addresses: [raft0.${DOMAIN}:7050,raft1.${DOMAIN}:7050,raft2.${DOMAIN}:7050]
            EtcdRaft:
              # The set of Raft replicas for this network. For the etcd/raft-based
              # implementation, we expect every replica to also be an OSN. Therefore,
              # a subset of the host:port items enumerated in this list should be
              # replicated under the Orderer.Addresses key above.
              Consenters:
                - Host: raft0.${DOMAIN}
                  Port: 7050
#                  ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft0.${DOMAIN}/msp/tlscacerts/tlsca.${DOMAIN}-cert.pem
                  ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft0.${DOMAIN}/tls/server.crt
                  ServerTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft0.${DOMAIN}/tls/server.crt
                - Host: raft1.${DOMAIN}
                  Port: 7050
#                  ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft1.${DOMAIN}/msp/tlscacerts/tlsca.${DOMAIN}-cert.pem
                  ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft1.${DOMAIN}/tls/server.crt
                  ServerTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft1.${DOMAIN}/tls/server.crt
                - Host: raft2.${DOMAIN}
                  Port: 7050
#                  ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft2.${DOMAIN}/msp/tlscacerts/tlsca.${DOMAIN}-cert.pem
                  ClientTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft2.${DOMAIN}/tls/server.crt
                  ServerTLSCert: ordererOrganizations/${DOMAIN}/orderers/raft2.${DOMAIN}/tls/server.crt
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities

        Consortiums:
            SampleConsortium:
                Organizations:
                    - *OrdererOrg


    CHANNEL:
        Orderer:
            Organizations:
            - *OrdererOrg
        Consortium: SampleConsortium
        Application:
            Organizations:
            - *firstOrg
            Capabilities:
                <<: *ApplicationCapabilities
            Policies:
              Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
              Writers:
                  Type: ImplicitMeta
                  Rule: "ANY Writers"
              Admins:
                Type: Signature
                Rule: "OutOf('1','${ORG}.admin')"
#              Admins:
#                  Type: ImplicitMeta
#                  Rule: "MAJORITY Admins"
